version: 2

integration_steps:
  ssh-keys:  &ssh-keys
    add_ssh_keys:
      fingerprints:
        - "50:b7:1d:44:fd:c4:f4:06:9a:4c:0f:16:0c:e1:3b:91"

  update-pip: &update-pip
    run:
      name: Update Pip
      command: |
        pip install -U pip


  install-docker-compose: &install-docker-compose
    run:
      name: Install Docker Compose
      command: |
        pip install docker-compose

  run-env: &run-env
    run:
      name: Get the environment up and running with Docker Compose
      command: |
        cd tests/integration && make && make run

  run-tests: &run-tests
    run:
      name: Run integration tests
      command: |
        cd tests/integration && make test

  dump-girder-logs: &dump-girder-logs
    run:
      name: Dump girder docker logs
      command: |
        cd tests/integration && docker-compose logs girder
      when: on_fail

  dump-worker-logs: &dump-worker-logs
    run:
      name: Dump girder_worker docker logs
      command: |
        cd tests/integration && docker-compose logs girder_worker
      when: on_fail


unit_steps:
  virtual-env: &virtual-env
    run:
      name: Setup virtual environment
      command: |
        if [ ! -d girder_env ]; then python -m virtualenv girder_env || python -m venv girder_env; fi
        echo ". $CIRCLE_WORKING_DIRECTORY/girder_env/bin/activate" >> $BASH_ENV

  ci-deps: &ci-deps
    run:
      name: Install CI dependencies
      command: pip install codecov tox

  upload-coverage: &upload-coverage
    run:
      name: Upload coverage to codecov
      command: coverage combine && codecov


jobs:
  py3_integration_tests:
    machine: true
    working_directory: /home/circleci/project
    steps:
      - run:
          name: Set up Python 3.6
          command: |
             pyenv install 3.6.3 || true
             pyenv global 3.6.3

      - *ssh-keys
      - checkout
      - *update-pip
      - *install-docker-compose
      - *run-env
      - *run-tests
      - *dump-girder-logs
      - *dump-worker-logs

  unit_tests:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - *virtual-env
      - *update-pip
      - *ci-deps
      - run:
          name: Run unit tests
          command: tox -e py36
      - *upload-coverage

  lint:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - *virtual-env
      - *update-pip
      - *ci-deps
      - run:
          name: Run linting tests
          command: tox -e lint

  release:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - *virtual-env
      - *update-pip
      - *ci-deps
      - run:
          name: Release to PyPI
          command: tox -e release


workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "17 2 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - py3_integration_tests

  ci:
    jobs:
      - unit_tests:
          filters:
            tags:
              only: /^v.*/
      - lint:
          filters:
            tags:
              only: /^v.*/
      - release:
          requires:
            - unit_tests
            - lint
          filters:
            tags:
              only: /^v.*/
            branches:
              only:
                - master
