FROM girder/girder_worker:latest
MAINTAINER Christopher Kotfila <chris.kotfila@kitware.com>

USER root

RUN sed -i  's|^broker.*=.*$|broker = amqp://guest:guest@rabbit/|' /girder_worker/girder_worker/worker.local.cfg

RUN apt-get update && apt-get install -y sudo

RUN apt-get install -y git

RUN pip install docker

VOLUME /girder_worker

# Make sure remote debugging is available
RUN pip install rpdb
# Make sure we have the newest girder_client
RUN pip install -U "git+https://github.com/girder/girder.git#egg=version_subpackage&subdirectory=clients/python"

COPY ./scripts /scripts

ENTRYPOINT ["/scripts/wait-for-it.sh", "rabbit:5672", "--", "/scripts/gw_entrypoint.sh"]
