FROM girder/girder:latest
MAINTAINER Christopher Kotfila <chris.kotfila@kitware.com>

RUN pip install ansible girder-client

COPY ./scripts /scripts
RUN mkdir -p /scripts/roles && ansible-galaxy install --roles-path /scripts/roles girder.girder

# Allow mounting /girder_worker
RUN mkdir /girder_worker
VOLUME /girder_worker

# Make sure remote debugging is available
RUN pip install rpdb

ENTRYPOINT ["/scripts/girder_entrypoint.sh"]
