FROM girder/girder_worker:latest
MAINTAINER Christopher Kotfila <chris.kotfila@kitware.com>

USER root

RUN sed -i  's|^broker =.*$|broker = amqp://guest:guest@rabbit/|' /girder_worker/girder_worker/worker.local.cfg

RUN apt update && apt install -y sudo
RUN pip install docker


VOLUME /girder_worker

# Make sure remote debugging is available
RUN pip install rpdb

# NOTE:  Change this to COPY before final commit
# COPY . /scripts
VOLUME /scripts

ENTRYPOINT ["/scripts/wait-for-it.sh", "rabbit:5672", "--", "/scripts/gw_entrypoint.sh"]
